apiVersion: v1
kind: Service
metadata:
  name: jenkinsapp-service
spec:
      containers:
      - name: "springcontsep13"
        image: "my-spring-appsep13" 
        ports:
            - containerPort: 8080
  
